---
title: "Analyysi kuntavaalien ehdokkaiden vaihtuvuudesta"
author: "Jakke Mäkelä"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

# Johdanto

Tässä raportissa analysoidaan kuntavaaliehdokkaiden vaihtuvuutta Suomen kuntavaaleissa 2012-2023. Tarkoituksena on selvittää, onko puolueiden välillä eroja siinä, miten paljon vaihtuvuutta ehdokkaissa on eri kuntavaalien välillä. 

Datat on haettu csv:nä 2023-05-03 oikeusministeriön palvelusta
https://tulospalvelu.vaalit.fi/

Skriptit löytyvät [githubista](https://github.com/JakkeMakela/kuntavaali_ehdokkuudet).

```{r include = FALSE}
source("global.R")
source("helpers.R")

dataDir <- "data"
cleanDataDir <- "cleandata"

isotPuolueet <- c("KOK", "KESK", "PS", "RKP", "SDP", "VAS", "VIHR" )

#pienPuolueet <- c("KD", "EOP", "FP", "LIBE", "LIIK", "PIR", "SKP")

testiPuolueet <- c(isotPuolueet)


puoluevarit <- c( "KOK" = "blue",
                  "KESK" = "lightgreen",
                  "PS" = "yellow",
                  "RKP" = "cyan",
                  "SDP" = "pink",
                  "VAS" = "red",
                  "VIHR" = "darkgreen" )


kuntakoodit <- getKuntaKoodit(2021, "data", "kuntakoodit_2021.csv")
vakiluku <- getVakiluvut(2022, "data", "vakiluku2022.csv")

```


```{r get_raw_data}

#Get raw data; Only need to run once
if (T){
  
  kv2021 <- getData(2021, "data", "ehd_maa_2021.csv")
  kv2017 <- getData(2017, "data", "ehd_maa_2017.csv")
  kv2012 <- getData(2012, "data", "ehd_maa_2012.csv") 
  fulldata <- kv2021 %>%
    bind_rows(kv2017) %>%
    bind_rows(kv2012)
  saveRDS(fulldata, paste0(cleanDataDir,"/kvdata.rds"))
  
  ek2023 <- getData(2023,  "data", "ehd_maa_ek_2023.csv")
  ek2019 <- getData(2019,  "data", "ehd_maa_ek_2019.csv")
  ek2015 <- getData(2015,  "data", "ehd_maa_ek_2015.csv")
  ek2011 <- getData(2011,  "data", "ehd_maa_ek_2011.csv")
  
  fulldata <- ek2023 %>%
    bind_rows(ek2019) %>%
    bind_rows(ek2015) %>%
    bind_rows(ek2011) 
  saveRDS(fulldata, paste0(cleanDataDir,"/ekdata.rds"))
  
  
}

```



```{r}

kvdata_raw <- readRDS(paste0(cleanDataDir,"/kvdata.rds")) %>%
  filter(puolue %in% testiPuolueet) 

ekdata_raw <- readRDS(paste0(cleanDataDir,"/ekdata.rds")) %>%
  filter(puolue %in% testiPuolueet) 

kokodata_raw <- rbind(kvdata_raw, ekdata_raw) %>%
  left_join(vakiluku, by = "kunta") %>% 
  mutate(kuntavaali = (vaali == "K")) 




kvtilasto <- teeTilasto(kokodata_raw %>% filter(kuntavaali), 
                        min.lista = 13, min.otos = 20)
ektilasto <- teeTilasto(kokodata_raw %>% filter (!kuntavaali), 
                        min.lista = 7, min.otos = 7)

kokotilasto <-bind_rows(kvtilasto, ektilasto)


kvdata <- left_join(kvdata_raw, kvtilasto)
ekdata <- left_join(ekdata_raw, ektilasto)
kokodata <- bind_rows(kvdata, ekdata)



```

```{r plot_tilasto}



plotTilasto(kvtilasto, 
            caption = "Vanhojen ehdokkaiden osuudet listalla, KV 2017-2021")

plotTilasto(kvtilasto, wrap = FALSE, 
            caption = "Vanhojen ehdokkaiden osuudet listalla, KV 2017-2021")


aov.kvtilasto <-  aov(vanhojen_osuus ~ puolue, data=kvtilasto)

summary(aov.kvtilasto)
coefficients(aov.kvtilasto)

```


```{r plot_ek}

plotTilasto(ektilasto, 
            caption = "Vanhojen ehdokkaiden osuudet, EK 2015-2023")

plotTilasto(ektilasto, wrap = FALSE, 
            caption = "Vanhojen ehdokkaiden osuudet, EK 2015-2023")

aov.ektilasto <-  aov(vanhojen_osuus ~ puolue, data=ektilasto)

summary(aov.ektilasto)
coefficients(aov.ektilasto)

```


```{r}

plotIka(kvdata, caption = "Ehdokkaiden ikajakaumat kuntavaaleissa" ,
        ymin=30, ymax=70) %>% print()

plotIka(ekdata, caption="Ehdokkaiden ikajakaumat ek-vaaleissa",
        ymin=30, ymax=70) %>% print()

```


```{r}

plotDistr(kvdata, "ika", caption = "Ehdokkaiden ikäjakaumat kuntavaaleissa" ,
        xmin=18, xmax=75) %>% print()


plotDistr(ekdata, "ika", caption = "Ehdokkaiden ikäjakaumat ek-vaaleissa" ,
        xmin=18, xmax=75) %>% print()

```

```{r}

plotDistr(kvdata %>% filter(aiemmin==TRUE), "ika",
             caption = "Kokeneiden ehdokkaiden ikäjakaumat kuntavaaleissa" ,
        xmin=18, xmax=75) %>% print()

```


```{r}

plotDistr(kvtilasto, "ika.ka",
             caption = "Listan keski-ikä kuntavaaleissa" ,
        xmin=35, xmax=60) %>% print()

```



```{r}
plotDistr(kvtilasto, "vanhojen_osuus",
             caption = "Kokeneiden osuus kuntavaaleissa" ,
        xmin=20, xmax=80) %>% print()
```


```{r}



plotIkaEffect(kvtilasto %>% filter(ika.ka <= 58), ymin=30, ymax = 70,
              caption = "KV, Listan keski-ika vs listan kokeneisuus") %>% 
  print()


```




```{r}
lm2 <- lmer(100*vanhojen_osuus ~ ika.ka +  1|puolue  , data = kvtilasto %>% filter(ika.ka <= 58))

summary(lm2)

coefficients(lm2)

```




```{r}


fd <- kvdata_raw %>%
  filter(ika < 55 & ika > 25)

ikamat <- fd %>%
  group_by(ika, puolue) %>%
  summarize(p.aiemmin = sum(aiemmin)/n())

plotIkaMat(ikamat, caption = "Kokemus iän funktiona")

lmika <- lmer(p.aiemmin ~ ika + 1|puolue, data = ikamat)
summary(lmika)
coefficients(lmika)


```



```{r}
lm.vanh <- lm(vanhojen_osuus ~ puolue*lista_maksimi , data = kvtilasto)

summary(lm.vanh)

```




```{r}

lm.ika <- lm(ika.ka ~ puolue*lista_maksimi , data = kvtilasto) 

summary(lm.ika)

```




```{r}

if (F){
  
  
  
  plotTilasto(kaikki, wrap = FALSE, 
              caption = "Vanhojen ehdokkaiden osuudet, EK&KV")
  
  aov.kaikki <-  aov(vanhojen_osuus ~ puolue, data=kokotilasto)
  
  summary(aov.kaikki)
  coefficients(aov.kaikki)
  
}

```



```{r}

if (F){
  plotTayttoaste <- function(data){
    
    
    plotdata <- data %>%
      mutate(vuosi=as.factor(vuosi)) %>%
      filter(tayttoaste <=1)
    
    medianval <- plotdata %>% pull(tayttoaste) %>% median()
    
    gx <- ggplot(plotdata, aes(x=reorder(puolue,tayttoaste,median, decreasing=TRUE), y=tayttoaste, col=puolue))+
      geom_boxplot()+
      geom_jitter(size=0.3,width=0.4, height=0.1,alpha=0.2)+
      geom_hline(yintercept=medianval,lty=2)+
      facet_wrap(~vuosi)+
      xlab("Puolueet")+
      ylab("Tayttoaste")
    ggtitle("Listan tayttoaste, 2019 & 2023")
    
    return(gx)
  }
  
  plotTayttoaste(kvtilasto)
}

```

